spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notes_db
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddlAuto: create-drop
    showSql: false

    # Performance optimization purposes, makes SQL execute faster
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      platform: postgres

# Cors config
cors:
  allowedOrigins: "http://localhost:3000,http://localhost:4200"
  allowedMethods: "POST,GET,PUT,DELETE"
  allowedHeaders: "*"
  exposedHeaders: "*"
