name: Java Spring Boot + AWS Fargate.
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - "main"

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build-infrastructure:
    if: false
    name: Terraform CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        working-directory: ./terraform

  build-and-deploy:
    name: Build and Deploy Docker Image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        id: configure-aws
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY --profile default
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
          aws configure set region $AWS_DEFAULT_REGION --profile default
          aws configure set output json --profile default

      - name: Login to ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - name: Build Docker Image
        id: build-image
        run: |
          docker build -t spring-boot-aws-fargate .

      - name: Tag Docker Image
        id: tag-image
        run: |
          docker tag spring-boot-aws-fargate:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/spring-boot-aws-fargate:latest

      - name: Push Docker Image to ECR
        id: push-image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/spring-boot-aws-fargate:latest
